---
- hosts: localhost
  tasks:
  - name: install pip requirments
    pip: name=docker-py version=1.6.0
    become: yes
    become_method: sudo

  - name: pull ngnix image
    docker_image: name=ngnix

  - name: make container
    docker: name=my_ngnix image=ngnix state=present

