---
- hosts: localhost
  tasks:
  - name: install pip requirments
    pip: name=docker-py version=1.6.0
    become: yes
    become_method: sudo

  - name: make container
    docker: name=my_ngnix image=ngnix state=present

  -name: create container with volume
   docker_container:
        name: my_web
        image: ngnix
        volumes:
           - ~/www:/usr/share/nginx/html:ro
        ports:
           - 8080:8080

