---
- hosts: localhost
  tasks:
  - name: install pip requirments
    pip: name=docker-py
  - name: pull ngnix image
    docker_image: name=ngnix

  - name: make container
    docker: name=my_ngnix image=ngnix state=present

